---
last_check:
  etag: '"a890dd4e39a04864adb9833a92fc13c7"'
  version: 1.8.9
  at: 1543541898
checked_completion: true
completion_version: 1.8.9
endpoints:
  https://api.travis-ci.org/:
    access_token: QzfY5UdioHUK3T8KkenoNA
repos:
  liupeng0518/gcr_sync:
    endpoint: https://api.travis-ci.org/
